---

- hosts: webservers
  
  # vars:
  #   - MyMessage: "Welcome to Ansible World!!"
  vars_files:
    - 'vars.yml'

  tasks:
    # - name: Install NGINX package
    #   apt: pkg=nginx state=installed update_cache=true
    #   when: ansible_os_family=="Debian"

    - name: Start NGINX service
      service: name=nginx enabled=yes state=started 
    
    # - name: Check file exisistance
    #   command: ls /usr/share/nginx/html/index.html
      #register: result

    # - name: check the result
    #   debug: var=result

  #   - name: Copy Site files
  #     template: src=templates/index.html.j2 dest=/var/www/html/index.nginx-debian.html
  #     #when: result.stat.exists
  #     notify: Restart NGINX

  # handlers:
  #   - name: Restart NGINX
  #     service: name=nginx state=restarted
