---
- hosts: webservers
  gather_facts: False
  # vars:
  #   - MyMessage: "Welcome to Ansible World!!"
  vars_files:
    - 'vars.yml'

  # tasks:
    # - name: Install NGINX package
    #   apt: pkg=nginx state=installed update_cache=true
    #   when: ansible_os_family=="Debian"

    # - name: Start NGINX service
    #   service: name=nginx enabled=yes state=started 
    
    # - name: Check file exisistance
    #   command: ls /usr/share/nginx/html/index.html
      #register: result

    # - name: check the result
    #   debug: var=result

  #   - name: Copy Site files
  #     template: src=templates/index.html.j2 dest=/var/www/html/index.nginx-debian.html
  #     #when: result.stat.exists
  #     notify: Restart NGINX

  # handlers:
  #   - name: Restart NGINX
  #     service: name=nginx state=restarted
    
    

  tasks:
    - name: Gather Server facts 
      setup: 
        filter: ansible_*
      register: result

    - name: Save IOS_facts to a file in a location
      copy: 
        content: "{{result | to_nice_json}}"
        dest: "~/Ansible-Learning/playbooks/Server_Excersises/Excersise2/Server_configurations/{{inventory_hostname}}_facts.json"