---


- hosts: playbooks
  gather_facts: false
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
    - name: Fancy way of doing authorized keys
      authorized_key: 
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  
  
