---
- hosts: allservers

  vars_files:
    - 'vars.yml'

  tasks:
    - name: Add line to end of the file
      lineinfile: 
        dest: /etc/sudoers 
        line: 'ubuntu ALL = NOPASSWD : ALL'
        state: present
        insertafter: EOF
        create: True