---
- hosts: allservers
  become: yes

  vars_files:
    - 'vars.yml'

  tasks:

    - name: check the line existence in file
      command: awk /^ubuntu/ /etc/sudoers 
      #shell: cat /etc/sudoers | egrep ubuntu
      register: check_line
      ignore_errors: True
      changed_when: false
    - debug: msg="{{check_line.stdout}}"


    - name: Add line to end of the file
      lineinfile: 
        dest: /etc/sudoers 
        line: 'ubuntu ALL = NOPASSWD : ALL'
        state: present
        insertafter: EOF
        create: True
      when: check_line.stdout == ""